var appConstants = {
  ADD_MESSAGE: "ADD_MESSAGE",
  ADD_USER: "ADD_USER",
  EDIT_USER: "EDIT_USER",
  GET_ALL_USERS: "GET_ALL_USERS",
  UPDATE_USERNAME:'UPDATE_USERNAME',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  VALIDATE_USER:'VALIDATE_USER'
};

module.exports = appConstants;
